IsTrustedSequencer = true
[Log]
Environment = "development"
Level = "debug"
Outputs = ["stderr","stdout"]

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "zkevm-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
FreeClaimGasLimit = 1500000
MaxTxBytesSize=30132
MaxTxDataBytesSize=30000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
    [Pool.DB]
    User = "pool_user"
    Password = "pool_password"
    Name = "pool_db"
    Host = "zkevm-pool-db"
    Port = "5432"
    EnableLog = false
    MaxConns = 200
[Etherman]
URL = "https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia"
MultiGasProvider = false
L1URL = "https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia"
L2URLs = ["http://84.247.161.133:8545"]
    [Etherman.Etherscan]
    ApiKey = "9e7d8e20-f69d-414c-a96c-142ad43b12b8"

[RPC]
Host = "0.0.0.0"
Port = 8545
ReadTimeoutInSec = 60
WriteTimeoutInSec = 60
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
BroadcastURI = "http://3.144.195.147:61090"
DefaultSenderAddress = "0x1111111111111111111111111111111111111111"
EnableL2SuggestedGasPricePolling = true
    [RPC.WebSockets]
            Enabled = true
            Port = 8546
[Synchronizer]
SyncInterval = "5s"
SyncChunkSize = 500
trustedSequencerURL = "http://84.247.161.133:8545"

[MTClient]
URI = "zkevm-prover:50061"

[Executor]
URI = "zkevm-prover:50071"

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = false

[Sequencer]
WaitPeriodPoolIsEmpty = "1s"
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
BlocksAmountForTxsToBeDeleted = 100
FrequencyToCheckTxsForDelete = "12h"
MaxTxsPerBatch = 150
MaxBatchBytesSize = 129848
MaxCumulativeGasUsed = 30000000
MaxKeccakHashes = 468
MaxPoseidonHashes = 279620
MaxPoseidonPaddings = 149796
MaxMemAligns = 262144
MaxArithmetics = 262144
MaxBinaries = 262144
MaxSteps = 8388608
WeightBatchBytesSize = 1
WeightCumulativeGasUsed = 1
WeightKeccakHashes = 1
WeightPoseidonHashes = 1
WeightPoseidonPaddings = 1
WeightMemAligns = 1
WeightArithmetics = 1
WeightBinaries = 1
WeightSteps = 1
TxLifetimeCheckTimeout = "10m"
MaxTxLifetime = "3h"
MaxTxSizeForL1 = 131072
    [Sequencer.Finalizer]
            GERDeadlineTimeoutInSec = "2s"
            ForcedBatchDeadlineTimeoutInSec = "60s"
            SendingToL1DeadlineTimeoutInSec = "20s"
            SleepDurationInMs = "100ms"
            ResourcePercentageToCloseBatch = 10
            GERFinalityNumberOfBlocks = 0
            ClosingSignalsManagerWaitForCheckingL1Timeout = "10s"
            ClosingSignalsManagerWaitForCheckingGER = "10s"
            ClosingSignalsManagerWaitForCheckingForcedBatches = "10s"
            ForcedBatchesFinalityNumberOfBlocks = 0
            TimestampResolution = "15s"
    [Sequencer.DBManager]
            PoolRetrievalInterval = "500ms"
    [Sequencer.Worker]
            ResourceCostMultiplier = 1000
[SequenceSender]
WaitPeriodSendSequence = "5s"
LastBatchVirtualizationTimeMaxWaitPeriod = "5s"
MaxTxSizeForL1 = 131072
SenderAddress = "0xeE7D0CF3a83e8fa70ad2B635A894EAbf6596C60b"
PrivateKeys = [{Path = "/pk/sequencer.keystore", Password = "password"}]

[Aggregator]
Host = "0.0.0.0"
Port = 50081
ForkId = 4
RetryTime = "5s"
VerifyProofInterval = "30s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "0x99E6f8a80EBE5fc1b9e7B3b58A3876D9062190A7"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"

[EthTxManager]
ForcedGas = 0
PrivateKeys = [
    {Path = "/pk/sequencer.keystore", Password = "password"},
    {Path = "/pk/aggregator.keystore", Password = "password"}
    ]
[Database]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "zkevm-bridge-db"
Port = "5435"
MaxConns = 20

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"

[NetworkConfig]
GenBlockNumber = 5217146
PolygonZkEVMAddress = "0x6918269Be0c377Dc6280855CD934a76B9B4aA597"
PolygonBridgeAddress = "0x16eDc524DD88ABc7551B101a04624cEBb53521bc"
PolygonZkEVMGlobalExitRootAddress = "0x43Fff8fa44DdD6dDE866F1EC4D42477aCDea180E"
MaticTokenAddress = "0x6Be539DC22Fe6b9d5ac33BBD86A8984F69CF101D"
L2PolygonBridgeAddresses = ["0x16eDc524DD88ABc7551B101a04624cEBb53521bc"]
L1ChainID = 11155111

[L2GasPriceSuggester]
Type = "default"
DefaultGasPriceWei = 100000000

[ClaimTxManager]
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/sequencer.keystore", Password = "password"}
Enabled = true
